table_name: "products"
catalog: "default"
schema: "public"
rows: 100
columns:
  - name: "product_id"
    type: "BIGINT"
    nullable: false
    comment: "Unique product identifier"
    primary_key: true
  
  - name: "product_name"
    type: "STRING"
    nullable: false
    comment: "Name of the product"
  
  - name: "price"
    type: "DECIMAL(10,2)"
    nullable: false
    comment: "Product price in USD"
  
  - name: "category"
    type: "STRING"
    nullable: true
    comment: "Product category"
  
  - name: "in_stock"
    type: "BOOLEAN"
    nullable: false
    comment: "Whether product is currently in stock"
  
  - name: "last_updated"
    type: "TIMESTAMP"
    nullable: false
    comment: "When the product information was last updated" 